### ISSUE TITLE
Project HTML

### ISSUE THREAD

**Issue by mhaidarhanif** [catamyst-community/codepolitan-1#1]
Project HTML

**Comment by mhaidarhanif** [comment]
Repo: https://github.com/mhaidarhanif/demo-html
Live: https://mhaidarhanif-demo-html.???.com

**Comment by nataliedk** [comment]
Repo: https://github.com/nataliedk/natdk.com

**Comment by ericprd** [comment]
Repo: https://github.com/ericprd/ericprd-web

**Comment by fikrialwan** [comment]
# Project HTML Fikri
Repo: https://github.com/fikrialwan/fikrialwan-web

**Comment by zul1996** [comment]
Project demo HTML
Repo: https://github.com/zul1996/demo-html
Project website HTML
Repo: https://github.com/zul1996/mzoel.com

**Comment by mohammadfarizan** [comment]
Repo: https://github.com/mohammadfarizan/demo-html

**Comment by naufalyukafi** [comment]
Repo: https://github.com/naufalyukafi/portfolio-v3

**Comment by nekkiichi** [comment]
Demo HTML
Repo: https://github.com/nekkiichi/demo-html

Project HTML
Repo: https://github.com/nekkiichi/adhinata.dev

**Comment by agnuramdan** [comment]
Repo : https://github.com/agnuramdan/agnuramdan-web

**Comment by dennnsh** [comment]
Repo: https://github.com/dennnsh/dennsh-web

**Comment by hisyamakbar** [comment]
Repo: https://github.com/hisyamakbar/hisyamakbar.com.git
Vercel: https://hisyamakbar-com.vercel.app/
