### ISSUE TITLE
Project Node.js

### ISSUE THREAD

**Issue by mhaidarhanif** [catamyst-community/codepolitan-1#12]
Project Node.js

**Comment by mohammadfarizan** [comment]
Repo: https://github.com/mohammadfarizan/demo-nodejs

**Comment by vektormuhammadlutfi** [comment]
repo : https://github.com/vektormuhammadlutfi/node-js-demo

**Comment by ersankarimi** [comment]
Repo : https://github.com/ersankarimi/bmi-calculator-copy
