### ISSUE TITLE
Project CSS

### ISSUE THREAD

**Issue by mhaidarhanif** [catamyst-community/codepolitan-1#2]
Project CSS

**Comment by mhaidarhanif** [comment]
Repo

**Comment by nekkiichi** [comment]
Repo: https://github.com/nekkiichi/adhinata.dev
Deploy Vercel: https://adhinata-dev.vercel.app/

**Comment by zul1996** [comment]
Repo : https://github.com/zul1996/demo-css

**Comment by dennnsh** [comment]
Repo: https://github.com/dennnsh/dennsh-web

Vercel: https://dennsh-web.vercel.app/

**Comment by fikrialwan** [comment]
Repo: https://github.com/fikrialwan/fikrialwan-web
Live on github pages: https://fikrialwan.github.io/fikrialwan-web/
Live on vercel : https://fikrialwan-web.vercel.app/

**Comment by ericprd** [comment]
Repo Demo CSS: https://github.com/ericprd/demo-css
Live on github pages: https://ericprd.github.io/demo-css

Repo Personal Web: https://github.com/ericprd/ericprd/ericprd-web
Live on Vercel: https://ericprd-web.vercel.app

**Comment by nataliedk** [comment]
Repo: https://github.com/nataliedk/demo-css

**Comment by ericprd** [comment]
> Repo: https://github.com/nataliedk/demo-css Live on Vercel: https://demo-css.vercel.app/

please check issues tab on your repository.

**Comment by mohammadfarizan** [comment]
Repo: https://github.com/mohammadfarizan/demo-css
Live on Vercel:  https://demo-css-taupe.vercel.app/

**Comment by agnuramdan** [comment]
Repo : https://github.com/agnuramdan/agnuramdan-web
Live on Vercel : https://agnuramdan-web.vercel.app/

**Comment by hisyamakbar** [comment]
Repo: https://github.com/hisyamakbar/experiment-css
