### ISSUE TITLE
Project Personal Website

### ISSUE THREAD

**Issue by mhaidarhanif** [catamyst-community/codepolitan-1#3]
Project Personal Website

**Comment by mhaidarhanif** [comment]
Repo: https://github.com/mhaidarhanif/mhaidarhanif-web
Live: https://mhaidarhanif.com

**Comment by ericprd** [comment]
Repo: https://github.com/ericprd/ericprd-web
Live: https://ericprd-web.vercel.app

**Comment by naufalyukafi** [comment]
repo: https://github.com/naufalyukafi/portfolio-v3 
live: https://yukafi-v3.vercel.app/

**Comment by dennnsh** [comment]
repo: https://github.com/dennnsh/dennsh-web

**Comment by fikrialwan** [comment]
repo: https://github.com/fikrialwan/fikrialwan-web
live: https://fikrialwan-web.vercel.app/

**Comment by zul1996** [comment]
repo: https://github.com/zul1996/mzoel.com
live: https://mzoel-com.vercel.app/

**Comment by agnuramdan** [comment]
repo: https://github.com/agnuramdan/agnuramdan-web
live: https://agnuramdan-web.vercel.app

**Comment by nekkiichi** [comment]
repo: https://github.com/nekkiichi/adhinata.dev
live: https://adhinata.dev

**Comment by nataliedk** [comment]
repo: https://github.com/nataliedk/natdk.com
web: https://natdk.com

**Comment by mohammadfarizan** [comment]
repo: https://github.com/mohammadfarizan/mohammadfarizan.com
web: mohammadfarizan.com

**Comment by mhaidarhanif** [comment]
@hisyamakbar & @baysatriow

**Comment by hisyamakbar** [comment]
Repo: https://github.com/hisyamakbar/hisyamakbar.com
Web: https://hisyamakbar.com/

**Comment by baysatriow** [comment]
Repo: (https://github.com/baysatriow/personal-website)
Web: (https://baysatriow.me)
