### ISSUE TITLE
Project Company Profile

### ISSUE THREAD

**Issue by mhaidarhanif** [catamyst-community/codepolitan-1#4]
Project Company Profile

- Inspirations: https://www.notion.so/catamystlearn/Company-websites-6abc397016a64861b7e240b50a770a90

**Comment by mhaidarhanif** [comment]
Repo: https://github.com/catamsyt-community/delight-web
Live: https://delight.vercel.app / https://delight.mhaidarhanif.com

**Comment by ericprd** [comment]
Repo: https://github.com/the-manabu/globalclean-web
Live: https://globalclean.ericprd.site

**Comment by nekkiichi** [comment]
Team 1:
Repo: https://github.com/urban-adam/urban-adam-web

**Comment by naufalyukafi** [comment]
Team 4:Yukafi @naufalyukafi & Agung @agnuramdan
Repo: https://github.com/De-Synq/de-synq

**Comment by dennnsh** [comment]
Team 2
