### ISSUE TITLE
Project CSS Flexbox

### ISSUE THREAD

**Issue by mhaidarhanif** [catamyst-community/codepolitan-1#5]
Project CSS Flexbox

- Docs: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox
- Guide: https://css-tricks.com/snippets/css/a-guide-to-flexbox
- Play: https://flexboxfroggy.com

**Comment by mhaidarhanif** [comment]
Repo: https://github.com/mhaidarhanif/demo-css-flexbox
Live:

**Comment by fikrialwan** [comment]
repo: https://github.com/fikrialwan/demo-flex-grid-responsive
live: https://fikrialwan.github.io/demo-flex-grid-responsive/

**Comment by zul1996** [comment]
repo : https://github.com/zul1996/mamipia.com
live : https://mamipia-com.vercel.app/

**Comment by nekkiichi** [comment]
repo: https://github.com/nekkiichi/learn-css-flex-n-grid
live: https://learn-css-flex-n-grid.vercel.app/css-grid.html

**Comment by dennnsh** [comment]
repo: https://github.com/dennnsh/learn-responsive-with-flexbox-grid
live: https://learn-flexbox-seven.vercel.app/

**Comment by naufalyukafi** [comment]
repo: https://github.com/naufalyukafi/catamyst-project/tree/main/css/flexbox

**Comment by agnuramdan** [comment]
repo: https://github.com/agnuramdan/demo-css-flexbox-grid
live: https://demo-css-flexbox-grid.vercel.app/

**Comment by ericprd** [comment]
repo: https://github.com/ericprd/flexbox-demo
live: https://flexbox-demo-six.vercel.app

**Comment by mohammadfarizan** [comment]
repo: https://github.com/mohammadfarizan/demo-css-flex-and-grid
live: https://demo-flex-and-grid.vercel.app/

**Comment by hisyamakbar** [comment]
repo: https://github.com/hisyamakbar/demo-css-flex-box

**Comment by nataliedk** [comment]
Repo: https://github.com/nataliedk/demo-css
