### ISSUE TITLE
Project CSS Grid

### ISSUE THREAD

**Issue by mhaidarhanif** [catamyst-community/codepolitan-1#6]
Project CSS Grid

- Docs: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids
- Guide: https://css-tricks.com/snippets/css/complete-guide-grid
- Play: https://cssgridgarden.com

**Comment by mhaidarhanif** [comment]
Repo: https://github.com/mhaidarhanif/demo-css-grid
Live:

**Comment by fikrialwan** [comment]
repo: https://github.com/fikrialwan/demo-flex-grid-responsive
live: https://fikrialwan.github.io/demo-flex-grid-responsive/

**Comment by zul1996** [comment]
repo : https://github.com/zul1996/mamipia.com
live : https://mamipia-com.vercel.app/

**Comment by nekkiichi** [comment]
repo: https://github.com/nekkiichi/learn-css-flex-n-grid
live: https://learn-css-flex-n-grid.vercel.app/css-grid.html

**Comment by dennnsh** [comment]
repo: https://github.com/dennnsh/learn-responsive-with-flexbox-grid
live: https://learn-flexbox-seven.vercel.app/

**Comment by naufalyukafi** [comment]
repo: https://github.com/naufalyukafi/catamyst-project/tree/main/css/grid

**Comment by agnuramdan** [comment]
repo: https://github.com/agnuramdan/demo-css-flexbox-grid
live: https://demo-css-flexbox-grid.vercel.app/

**Comment by ericprd** [comment]
repo: https://github.com/ericprd/responsive-grid
live: https://responsive-grid-theta.vercel.app

**Comment by nataliedk** [comment]
Repo: https://github.com/nataliedk/demo-css-grid-responsive
Live: https://demo-css-grid-responsive.vercel.app/
